### ISSUE TITLE
'useDeEncrypt' is not defined

### ISSUE THREAD

**Issue by geckiss** [crazko/use-dencrypt-effect#1]
Installed with `yarn add use-dencrypt-effect`, literally **copied** usage example and got error `'useDeEncrypt' is not defined  no-undef`.

`import { useDencrypt } from "use-dencrypt-effect";` is grayed out.

**Comment by crazko** [comment]
Thanks for pointing out this issue. You are right, there's a typo in the example. This is how it should be used:

```diff
import React from "react";
import { useDencrypt } from "use-dencrypt-effect";

const Example = () => {
-  const { result, deEncrypt } = useDeEncrypt();
+  const { result, dencrypt } = useDencrypt();

// ...
```

I'll update README soon.

**Comment by geckiss** [comment]
Works, thanks!
