### ISSUE TITLE
Callback if animation finished

### ISSUE THREAD

**Issue by exocode** [crazko/use-dencrypt-effect#2]
Hi, and thank you for this really nice animation plugin. 

My question (or feature request) is: 

- Is there a way to get a callback if the animation is finished?
(I have a navigation when I hover, the animation starts. But when I leave the NavItem, I wanna be able to finish the animation. Maybe you can suggest me an solution: Here is a codesandbox to show my problem: https://codesandbox.io/s/use-dencrypt-effect-m0cez?file=/src/index.js:304-395

thank you in advance

**Comment by crazko** [comment]
Hi, currently there's no option for callback when animation finished.
Here is a naive implementation of what you probably try to achieve https://codesandbox.io/s/use-dencrypt-effect-lh1s0?file=/src/index.js
I used [`interval` option](https://github.com/crazko/use-dencrypt-effect/blob/master/src/index.tsx#L50) to calculate the time when to switch the state.
It's not nice, but could work... :)

**Comment by exocode** [comment]
ah, nice, thank you very much! simple but exactly what I need
