### ISSUE TITLE
Starts with Empty Text

### ISSUE THREAD

**Issue by alexbaker2002** [crazko/use-dencrypt-effect#3]
As the method loads, the page is blank, so it looks as if it hangs. Is there a way to begin with some default text from the array before the animation begins?

Thanks

**Comment by crazko** [comment]
Hi Alex, thanks for the question.

Unfortunately, there no such option implemented currently. But I too think it could be a nice addition.

Will think about the solution, though, can't promise when it'll bee done.

**Comment by crazko** [comment]
I've implemented some enhancement, but it's still a bit buggy. Need more time for that.

**Comment by bmbejcek** [comment]
Hi there @crazko. Any documentation on how to take care of the enhancement you mentioned? Love the package but am looking for a way to not start with blank text.

**Comment by crazko** [comment]
Hi, not yet, unfortunately. I'm still looking for the final solution.

**Comment by crazko** [comment]
I've just published new, improved version that can contain initial value and should be capable of running the effect with identical words. API has changed, so it's a major pre-release `2.0.0-rc.1`. More info in https://github.com/crazko/use-dencrypt-effect/blob/feature/initial/README.md, it also contains examples. 

Please, try it and let me know if it behaves correctly.

**Comment by bmbejcek** [comment]
Woah, this is awesome!! Thanks @crazko
