### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by samba0648** [crazko/use-dencrypt-effect#5]
Hi,
I'm new to react. I don't know how to run this hook.
Just I have used this as it.  But the text effect is not running infinitely. Can you please help with this problem?
The effect is running only one.

**Comment by crazko** [comment]
Can you show the code? Maybe upload the example on https://codesandbox.io/. I can't help without seeing anything.

**Comment by samba0648** [comment]
https://codesandbox.io/s/nifty-shaw-v7ybq?fontsize=14&hidenavigation=1&theme=dark
Actually, my problem is I want the same word to show up many times

**Comment by samba0648** [comment]
Actually the code is working when we use two or more different words. for a single word or for same words it is not working.

**Comment by crazko** [comment]
Hi, thanks for your example. Actually it is connected with #3 I'm still looking for the final solution.

**Comment by crazko** [comment]
I've just published new, improved version that should be capable of running the effect with identical words. API has changed, so it's a major pre-release `2.0.0-rc.1`. More info in https://github.com/crazko/use-dencrypt-effect/blob/feature/initial/README.md, it also contains examples. 

Please, try it and let me know if it behaves correctly.
