### ISSUE TITLE
Wrong package version install

### ISSUE THREAD

**Issue by MasoudAbdaal** [crazko/use-dencrypt-effect#6]
**Steps to reproduce**
- Create a new react project.
- Run `npm install --save use-dencrypt-effect`

**Expected result**
Package.json has `use-dencrypt-effect` with version `1.0.1` and uses the same API as the examples.

**Actual result**
Package.json has `use-dencrypt-effect` with version `2.0.0-rc.1` and uses the different API than the examples.

**Comment by crazko** [comment]
Hi, thanks for pointing this out. I tried to set `next` tag to the release candidate version, so now it should work as expected:

- `npm i use-dencrypt-effect` -> installs `1.0.2` version
- `npm i use-dencrypt-effect@next` -> installs `2.0.0-rc.1` version

```
npm dist-tag ls use-dencrypt-effect
latest: 1.0.2
next: 2.0.0-rc.1
```

More RC versions will come, as I'm still not sure with the new implementation as well as have some more ideas how to decouple it.
